spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.kwpkidgxsuyzgbkpbqlq&password=@123!456@789
    username: postgres.kwpkidgxsuyzgbkpbqlq
    password: "@123!456@789"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false

server:
  port: 8080