version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: sop_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.acrjojwjeuvqtonmklci
      - SPRING_DATASOURCE_PASSWORD=Batholomeo.249249
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    restart: always
    networks:
      - sop-network
  frontend:
    build:
      context: ./frontend
    container_name: sop_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - sop-network
networks:
  sop-network:
    driver: bridge